id: I20F64545
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:49:35+00:00'
last_modified: '2022-06-09T05:13:02.059891+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD2074
  title: གཡུ་ཐོག་སྙིང་ཐིག་སྐོར་ཕྱོགས་སྒྲིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8270':
      image_group_id: I4PD2076
      title: ''
      total_pages: 558
      order: 1
      base_file: 8270.txt
    88F9:
      image_group_id: I4PD2077
      title: ''
      total_pages: 642
      order: 2
      base_file: 88F9.txt
    A6A6:
      image_group_id: I4PD2078
      title: ''
      total_pages: 684
      order: 3
      base_file: A6A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
