id: I20F64545
legacy_id: P008203
ocr_import_info:
  bdrc_scan_id: W4PD2074
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T18:45:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:20:10.396979+00:00'
last_modified: 2022-09-04 05:20:53.438472
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD2074
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD2074
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཡུ་ཐོག་སྙིང་ཐིག་སྐོར་ཕྱོགས་སྒྲིག
  author: གཡུ་ཐོག་རྙིང་མ་ཡོན་ཏན་མགོན་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9371829591757791
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD2077:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2077
      total_pages: 642
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD2077.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.93099247060193
    legacy_id: v002
  I4PD2076:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2076
      total_pages: 558
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD2076.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.945784317699502
    legacy_id: v001
  I4PD2078:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2078
      total_pages: 684
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD2078.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9370239623110171
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
