id: P008203
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD2074
  title: གཡུ་ཐོག་སྙིང་ཐིག་སྐོར་ཕྱོགས་སྒྲིག
  author: ''
  volumes:
    1f23a889c87d4771973d8d3fdf8a6ae2:
      image_group_id: I4PD2076
      title: ''
      volume_number: 1
      total_pages: 558
    3ec15e25d36440bda44687f972a36d24:
      image_group_id: I4PD2077
      title: ''
      volume_number: 2
      total_pages: 642
    6cc42341ae294c57bfa9f71719c53f41:
      image_group_id: I4PD2078
      title: ''
      volume_number: 3
      total_pages: 684
